# Generated by Django 4.1 on 2023-09-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentprofile", name="user",),
        migrations.RemoveField(model_name="teacherprofile", name="user",),
        migrations.DeleteModel(name="Student",),
        migrations.DeleteModel(name="Teacher",),
        migrations.RemoveField(model_name="customuser", name="role",),
        migrations.DeleteModel(name="StudentProfile",),
        migrations.DeleteModel(name="TeacherProfile",),
    ]
