# Generated by Django 4.1 on 2023-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0003_alter_relationship_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="status",
            field=models.CharField(
                choices=[("sent", "sent"), ("accepted", "accepted")], max_length=8
            ),
        ),
    ]
