# Generated by Django 4.1 on 2023-08-30 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
